apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/

patches:
  - path: sm.yaml
  - path: json6902.yaml
    target:
      kind: Deployment
      name: web-deployment